#ifndef __IREADERERROR__
#define __IREADERERROR__

#define IREADER_SUCCESS				0
#define IREADER_NOT_INTIALIZED		1
#define IREADER_HANDLE_INVALID		2
#define IREADER_NOT_CONNECTED		3
#define IREADER_TIMEOUT_1			4
#define IREADER_TIMEOUT_2			5
#define IREADER_INVALID				6
#define IREADER_CONNECT_FAIL		7
#define	IREADER_NO_ANTENNA			8
#define IREADER_COMMAND_FAIL		9
#define IREADER_SLAVE_NO_RESPONSE	10
#define IREADER_WRITE_TAG_FAIL	    11
#define IREADER_WRITE_TAG_DENY	    12
#define IREADER_MUTEX_FAIL	    	13
#define	IREADER_SET_POWER_FAIL		14
#define IREADER_SOCKET_ERROR		-1

#endif